iced.catchExceptions()

delay = (cb) ->
  await setTimeout defer(), 100
  cb()
class X
  go : (cb) -> 
    await delay defer()
    throw new Error "yuck!"
class C
  constructor : ->
    @x = new X()
  a : (cb) ->
    await delay defer()
    await @b defer()
  b : (cb) ->
    await delay defer()
    await @c defer()
  c : (cb) ->
    await delay defer()
    await @x.go defer()
    cb();
top = ->
  c = new C
  await c.a defer()
top() 
